//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputAction/CharacterAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterAction"",
    ""maps"": [
        {
            ""name"": ""OnGround"",
            ""id"": ""dcdf4dc3-0be6-457e-a0b3-fa139df8b0bb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""96bf80de-5dc0-484c-9fc0-84f01b0bb579"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""UseTools"",
                    ""type"": ""Button"",
                    ""id"": ""2ae0f915-da42-46bd-8e53-e12af81cf75a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem1"",
                    ""type"": ""Button"",
                    ""id"": ""7d052126-a182-4b7f-a577-e415e3b46d57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem2"",
                    ""type"": ""Button"",
                    ""id"": ""d2bce54c-ec8e-4291-919b-687cbc0586b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem3"",
                    ""type"": ""Button"",
                    ""id"": ""73fd5574-dfe3-4b0c-b37e-0e25eceb9a0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem4"",
                    ""type"": ""Button"",
                    ""id"": ""b922ff26-f910-4321-aeb8-ed37021cca27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem5"",
                    ""type"": ""Button"",
                    ""id"": ""729366dc-010e-49c6-bea7-05fcfd0a5491"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem6"",
                    ""type"": ""Button"",
                    ""id"": ""db8e2ae3-bc88-4156-b593-46e61033b5a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem7"",
                    ""type"": ""Button"",
                    ""id"": ""e029addf-ac36-4308-b007-7903bd647427"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem8"",
                    ""type"": ""Button"",
                    ""id"": ""ef7d5d99-17ea-45fb-a19f-10aa84647049"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem9"",
                    ""type"": ""Button"",
                    ""id"": ""56fe1b63-10af-41c0-9a9e-b9858b42614f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem10"",
                    ""type"": ""Button"",
                    ""id"": ""aed70024-3c61-43d2-8614-5c941a17568c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7ec46996-ef97-4673-8dc5-a026dffa3796"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""683f7820-8832-4902-9dda-3e8cb8d668c8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""19d70b04-7905-4937-9cdc-4bbd2da67573"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""867875eb-1644-44d6-9657-1365048b3bf9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""db507b60-26e9-420d-b33f-9a008fc8195a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""af4023ca-89cb-446a-9b4e-f968ac6fc61d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2603b776-b8cd-4d06-9308-d2e24e94d48b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""933645b9-bc0a-4a29-b695-9ce4a45c59ba"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6232ff9d-6f96-46d3-9e16-920b5021143c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5fc44313-e301-481a-90a5-959e1f504819"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dba55dba-ba4f-4c84-81dd-cdadfb975451"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2c28e93-918a-49e9-bfda-a9d76e965630"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbafb64e-ff4b-4021-a879-d702a813a009"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseTools"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""198ed19d-ed8c-41e0-b9a5-4a2796e13b8d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1ea29d6-797b-4861-9155-acf5e3bed6f0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37f451d0-6624-42a6-ac3b-7fbfbcc504fb"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c80e05a7-6803-4d89-93be-3eb0f3c8a3be"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d59b407-526a-4e52-8970-99667ccfb6cf"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12bf29a8-0642-4ea2-a108-e36e68469fb7"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5e0576b-a31e-4b43-89de-79f1ce30ba9c"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44a48664-bf95-44d8-a27a-7e4c8d29f10a"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05fa8750-1396-4080-b9a0-e081c0615e2c"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa108230-ec6b-43f1-9337-d65ebd4d3c07"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // OnGround
        m_OnGround = asset.FindActionMap("OnGround", throwIfNotFound: true);
        m_OnGround_Move = m_OnGround.FindAction("Move", throwIfNotFound: true);
        m_OnGround_UseTools = m_OnGround.FindAction("UseTools", throwIfNotFound: true);
        m_OnGround_UseItem1 = m_OnGround.FindAction("UseItem1", throwIfNotFound: true);
        m_OnGround_UseItem2 = m_OnGround.FindAction("UseItem2", throwIfNotFound: true);
        m_OnGround_UseItem3 = m_OnGround.FindAction("UseItem3", throwIfNotFound: true);
        m_OnGround_UseItem4 = m_OnGround.FindAction("UseItem4", throwIfNotFound: true);
        m_OnGround_UseItem5 = m_OnGround.FindAction("UseItem5", throwIfNotFound: true);
        m_OnGround_UseItem6 = m_OnGround.FindAction("UseItem6", throwIfNotFound: true);
        m_OnGround_UseItem7 = m_OnGround.FindAction("UseItem7", throwIfNotFound: true);
        m_OnGround_UseItem8 = m_OnGround.FindAction("UseItem8", throwIfNotFound: true);
        m_OnGround_UseItem9 = m_OnGround.FindAction("UseItem9", throwIfNotFound: true);
        m_OnGround_UseItem10 = m_OnGround.FindAction("UseItem10", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnGround
    private readonly InputActionMap m_OnGround;
    private List<IOnGroundActions> m_OnGroundActionsCallbackInterfaces = new List<IOnGroundActions>();
    private readonly InputAction m_OnGround_Move;
    private readonly InputAction m_OnGround_UseTools;
    private readonly InputAction m_OnGround_UseItem1;
    private readonly InputAction m_OnGround_UseItem2;
    private readonly InputAction m_OnGround_UseItem3;
    private readonly InputAction m_OnGround_UseItem4;
    private readonly InputAction m_OnGround_UseItem5;
    private readonly InputAction m_OnGround_UseItem6;
    private readonly InputAction m_OnGround_UseItem7;
    private readonly InputAction m_OnGround_UseItem8;
    private readonly InputAction m_OnGround_UseItem9;
    private readonly InputAction m_OnGround_UseItem10;
    public struct OnGroundActions
    {
        private @CharacterAction m_Wrapper;
        public OnGroundActions(@CharacterAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_OnGround_Move;
        public InputAction @UseTools => m_Wrapper.m_OnGround_UseTools;
        public InputAction @UseItem1 => m_Wrapper.m_OnGround_UseItem1;
        public InputAction @UseItem2 => m_Wrapper.m_OnGround_UseItem2;
        public InputAction @UseItem3 => m_Wrapper.m_OnGround_UseItem3;
        public InputAction @UseItem4 => m_Wrapper.m_OnGround_UseItem4;
        public InputAction @UseItem5 => m_Wrapper.m_OnGround_UseItem5;
        public InputAction @UseItem6 => m_Wrapper.m_OnGround_UseItem6;
        public InputAction @UseItem7 => m_Wrapper.m_OnGround_UseItem7;
        public InputAction @UseItem8 => m_Wrapper.m_OnGround_UseItem8;
        public InputAction @UseItem9 => m_Wrapper.m_OnGround_UseItem9;
        public InputAction @UseItem10 => m_Wrapper.m_OnGround_UseItem10;
        public InputActionMap Get() { return m_Wrapper.m_OnGround; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnGroundActions set) { return set.Get(); }
        public void AddCallbacks(IOnGroundActions instance)
        {
            if (instance == null || m_Wrapper.m_OnGroundActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnGroundActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @UseTools.started += instance.OnUseTools;
            @UseTools.performed += instance.OnUseTools;
            @UseTools.canceled += instance.OnUseTools;
            @UseItem1.started += instance.OnUseItem1;
            @UseItem1.performed += instance.OnUseItem1;
            @UseItem1.canceled += instance.OnUseItem1;
            @UseItem2.started += instance.OnUseItem2;
            @UseItem2.performed += instance.OnUseItem2;
            @UseItem2.canceled += instance.OnUseItem2;
            @UseItem3.started += instance.OnUseItem3;
            @UseItem3.performed += instance.OnUseItem3;
            @UseItem3.canceled += instance.OnUseItem3;
            @UseItem4.started += instance.OnUseItem4;
            @UseItem4.performed += instance.OnUseItem4;
            @UseItem4.canceled += instance.OnUseItem4;
            @UseItem5.started += instance.OnUseItem5;
            @UseItem5.performed += instance.OnUseItem5;
            @UseItem5.canceled += instance.OnUseItem5;
            @UseItem6.started += instance.OnUseItem6;
            @UseItem6.performed += instance.OnUseItem6;
            @UseItem6.canceled += instance.OnUseItem6;
            @UseItem7.started += instance.OnUseItem7;
            @UseItem7.performed += instance.OnUseItem7;
            @UseItem7.canceled += instance.OnUseItem7;
            @UseItem8.started += instance.OnUseItem8;
            @UseItem8.performed += instance.OnUseItem8;
            @UseItem8.canceled += instance.OnUseItem8;
            @UseItem9.started += instance.OnUseItem9;
            @UseItem9.performed += instance.OnUseItem9;
            @UseItem9.canceled += instance.OnUseItem9;
            @UseItem10.started += instance.OnUseItem10;
            @UseItem10.performed += instance.OnUseItem10;
            @UseItem10.canceled += instance.OnUseItem10;
        }

        private void UnregisterCallbacks(IOnGroundActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @UseTools.started -= instance.OnUseTools;
            @UseTools.performed -= instance.OnUseTools;
            @UseTools.canceled -= instance.OnUseTools;
            @UseItem1.started -= instance.OnUseItem1;
            @UseItem1.performed -= instance.OnUseItem1;
            @UseItem1.canceled -= instance.OnUseItem1;
            @UseItem2.started -= instance.OnUseItem2;
            @UseItem2.performed -= instance.OnUseItem2;
            @UseItem2.canceled -= instance.OnUseItem2;
            @UseItem3.started -= instance.OnUseItem3;
            @UseItem3.performed -= instance.OnUseItem3;
            @UseItem3.canceled -= instance.OnUseItem3;
            @UseItem4.started -= instance.OnUseItem4;
            @UseItem4.performed -= instance.OnUseItem4;
            @UseItem4.canceled -= instance.OnUseItem4;
            @UseItem5.started -= instance.OnUseItem5;
            @UseItem5.performed -= instance.OnUseItem5;
            @UseItem5.canceled -= instance.OnUseItem5;
            @UseItem6.started -= instance.OnUseItem6;
            @UseItem6.performed -= instance.OnUseItem6;
            @UseItem6.canceled -= instance.OnUseItem6;
            @UseItem7.started -= instance.OnUseItem7;
            @UseItem7.performed -= instance.OnUseItem7;
            @UseItem7.canceled -= instance.OnUseItem7;
            @UseItem8.started -= instance.OnUseItem8;
            @UseItem8.performed -= instance.OnUseItem8;
            @UseItem8.canceled -= instance.OnUseItem8;
            @UseItem9.started -= instance.OnUseItem9;
            @UseItem9.performed -= instance.OnUseItem9;
            @UseItem9.canceled -= instance.OnUseItem9;
            @UseItem10.started -= instance.OnUseItem10;
            @UseItem10.performed -= instance.OnUseItem10;
            @UseItem10.canceled -= instance.OnUseItem10;
        }

        public void RemoveCallbacks(IOnGroundActions instance)
        {
            if (m_Wrapper.m_OnGroundActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnGroundActions instance)
        {
            foreach (var item in m_Wrapper.m_OnGroundActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnGroundActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnGroundActions @OnGround => new OnGroundActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IOnGroundActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnUseTools(InputAction.CallbackContext context);
        void OnUseItem1(InputAction.CallbackContext context);
        void OnUseItem2(InputAction.CallbackContext context);
        void OnUseItem3(InputAction.CallbackContext context);
        void OnUseItem4(InputAction.CallbackContext context);
        void OnUseItem5(InputAction.CallbackContext context);
        void OnUseItem6(InputAction.CallbackContext context);
        void OnUseItem7(InputAction.CallbackContext context);
        void OnUseItem8(InputAction.CallbackContext context);
        void OnUseItem9(InputAction.CallbackContext context);
        void OnUseItem10(InputAction.CallbackContext context);
    }
}
